Update dependencies
RockefellerArchiveCenter/request_broker pull request #124
Opened 2021-06-30 19:02 UTC by p-galligan

Updates dependencies.

Adds dependabot.

Adds requirements.in

2021-06-30 21:20 UTC, helrond requested changes
I think you can get rid of the `coverage` requirement. Otherwise, looks good!

2021-06-30 21:20 UTC, helrond commented on requirements.in
> +coverage==5.5
This does not appear to be used anywhere.

2021-07-01 13:27 UTC, helrond approved these changes

2021-07-01 20:48 UTC, HaSistrunk approved these changes
Makes sense to me!

2021-07-02 20:28 UTC, bonniegee approved these changes

2021-07-02 20:40 UTC, merged