Use get_url method in resolver view
RockefellerArchiveCenter/request_broker pull request #217
Opened 2022-08-15 21:51 UTC by helrond

Slightly refactors `get_url` method to make it more flexible, and then uses that method in link resolver to return accurate DIMES URLs.

Fixes #216

2022-09-23 19:35 UTC, ctgraham requested changes
Proposed patch:
```
diff --git a/process_request/helpers.py b/process_request/helpers.py
index d4cbf2b..6bbfa79 100644
--- a/process_request/helpers.py
+++ b/process_request/helpers.py
@@ -376,10 +376,10 @@ def get_parent_title(obj_json):


 def get_url(obj_json, client, host=None):
-    """Returns a full URL for an object."""
+    """Returns a full or relative URL for an object, depending on if a host is provided."""
     uuid = shortuuid.uuid(name=obj_json["uri"])
     path = "collections" if has_children(obj_json, client) else "objects"
-    return "{}/{}/{}".format(host, path, uuid) if host else "/objects/{}".format(uuid)
+    return "{}/{}/{}".format(host, path, uuid) if host else "/{}/{}".format(path, uuid)


 def has_children(obj_json, client):
@@ -415,23 +415,6 @@ def list_chunks(lst, n):
         yield lst[i:i + n]


-def identifier_from_uri(uri):
-    """Creates a short UUID.
-
-    Uses `shortuuid`, which first creates a v5 UUID using an object's AS URI as
-    a name, and then converts them to base57 using lowercase and uppercase
-    letters and digits, and removing similar-looking characters such as
-    l, 1, I, O and 0.
-
-    This is a one-way process; while it is possible to consistently generate a
-    given UUID given an AS URI, it is not possible to decode the URI from the
-    UUID.
-
-    Helper method copied from https://github.com/ulsdevteam/pisces/blob/base/fetcher/helpers.py#L81
-    """
-    return shortuuid.uuid(name=uri)
-
-
 def resolve_ref_id(repo_id, ref_id, client):
     """ Accepts options to find archival objects using find_by_id method.

diff --git a/process_request/views.py b/process_request/views.py
index 762b699..1cd7e25 100644
--- a/process_request/views.py
+++ b/process_request/views.py
@@ -124,7 +124,7 @@ class LinkResolverView(APIView):
             host = settings.RESOLVER_HOSTNAME
             repo = settings.ARCHIVESSPACE["repo_id"]
             uri = resolve_ref_id(repo, data, aspace.client)
-            response = redirect("//{}{}".format(host, uri))
+            response = redirect("{}{}".format(host, uri))
             return response
         except Exception as e:
             return Response({"detail": str(e)}, status=500)

```

2022-09-23 19:35 UTC, ctgraham commented on process_request/helpers.py
> +    return "{}/{}/{}".format(host, path, uuid) if host else "/objects/{}".format(uuid)
The `else` condition should also honor the `path` variable.

2022-09-23 19:35 UTC, ctgraham commented on process_request/helpers.py
> +    return get_url(aspace_obj, client)
This change orphans the `identifier_from_uri` method, which can be removed.

2022-09-23 19:35 UTC, ctgraham commented on process_request/helpers.py
> +def get_url(obj_json, client, host=None):
The doc says this returns a "full URL", which is not always true.  It could return a full URL or a relative URI, depending on if the host is passed.

2022-09-23 19:35 UTC, ctgraham commented on process_request/helpers.py
> +    Generates and returns a DIMES URI from an ArchiveSpace URI.
By changing this return from an "id" to a URI, we gain a leading slash.  The caller in `LinkResolverView` in `process_request/views.py` is the only current caller, and needs to be updated.

2022-09-23 19:44 UTC, ctgraham commented
An aside here:
`RESOLVER_HOSTNAME` is an alias for `DIMES_HOSTNAME`

https://github.com/RockefellerArchiveCenter/request_broker/blob/073d09b56ba76e915b3606475aee6ac819253344/request_broker/settings.py#L155

It is only used in three lines:
```
$ grep -rF RESOLVER_HOSTNAME
process_request/views.py:            host = settings.RESOLVER_HOSTNAME
process_request/tests.py:            self.assertEqual(response.url, f"{settings.RESOLVER_HOSTNAME}/objects/{mock_uri}")
request_broker/settings.py:RESOLVER_HOSTNAME = config.DIMES_HOSTNAME
```

Is there justification for it existing as an independent variable name?  Or could we just replace it with `DIMES_HOSTNAME`?

2022-09-26 17:45 UTC, helrond commented
Thanks so much for this review @ctgraham. I think I have resolved most of the issues.

Regarding the hostname, the rationale for at the time preserving that config was that there is a conceivable scenario where a link resolver might target a system other than DIMES. However, thinking about that now, it occurs to me that the logic here which resolves AS ref_ids _is_ in fact specific to DIMES so that approach makes less sense to me know than it did previously.

Looking at this also led me to realize that the hostname config is really a hostname, (i.e. without the protocol or port) and what we really needed here was a base URL, which would save us from prefixing with the config in a number of places in views. I'm going to make that tweak as well.

2022-09-29 14:00 UTC, ctgraham approved these changes
Code has a good read-through, and the clarification of the `DIMES_HOSTNAME` / `DIMES_BASEURL` resolves an outstanding confusion of mine.  Built and tested locally against our instance.

2022-10-04 18:43 UTC, merged