Update readme
RockefellerArchiveCenter/request_broker pull request #51
Opened 2020-08-05 13:42 UTC by p-galligan

Updates readme to fill in as much as possible. Routes are incomplete as of now, but will be extended as necessary. Fixes #46

2020-08-05 14:02 UTC, bonniegee approved these changes

2020-08-06 19:56 UTC, p-galligan commented
Sorry @helrond @HaSistrunk I thought I asked for your review on this as well. Adding you now.

2020-08-06 21:35 UTC, helrond requested changes

2020-08-06 21:35 UTC, helrond commented on README.md
> +* Iterates over a list of request URIs and gets corresponding data from ArchivesSpace and parses over the data and marks it as submittable or unsubmittable.
```suggestion
* Request Pre-Processing: Iterates over a list of request URIs, fetches corresponding data from ArchivesSpace, parses the data and marks it as submittable or unsubmittable.
```

2020-08-06 21:35 UTC, helrond commented on README.md
> +* Converts AS data into strings and it to the message body of an email and then sends an email to an address or list of addresses.
```suggestion
* Mailer: correctly formats the body of an email message and sends an email to an address or list of addresses.
```

2020-08-06 21:35 UTC, helrond commented on README.md
> +* Creates retrieval and duplication transactions in Aeon by sending data to the Aeon API.
```suggestion
* Aeon Request Submission: creates retrieval and duplication transactions in Aeon by sending data to the Aeon API.
```

2020-08-06 21:35 UTC, helrond commented on README.md
>  ## Services
There's also the CSV Download service that's missing.

2020-08-07 15:32 UTC, helrond approved these changes

2020-08-07 18:10 UTC, HaSistrunk commented on README.md
> +An application that accepts requests with lists of ArchivesSpace URIs from users of our discovery system and for each item grabs data from ArchivesSpace. Formats that data for delivery to our item re
```suggestion
An application that accepts requests with lists of ArchivesSpace URIs from users of our discovery system. For each item, the application fetches data from ArchivesSpace, formats that data for delivery to our retrieval management system (Aeon) to enable reading room or duplication requests, or formats the data for email delivery or CSV download. It routes formatted data to the retrieval system or to an email for researcher use. This is a passthrough service; users cannot create requests directly in the application.
```

2020-08-07 18:12 UTC, HaSistrunk commented
Looks good - I just had a few suggestions to make that first paragraph a little clearer.

2020-08-07 18:53 UTC, HaSistrunk approved these changes

2020-08-07 18:54 UTC, merged